// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  // Defaults to dev, not prod: an unset FIREBASE_ENV should fail safe toward
  // throwaway data, not real user data. Release builds set this explicitly
  // (see ios/fastlane/Fastfile's ensure_prod_firebase_config!) rather than
  // relying on this default.
  static const String firebaseEnv = String.fromEnvironment(
    'FIREBASE_ENV',
    defaultValue: 'dev',
  );

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return _webForEnv;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return _androidForEnv;
      case TargetPlatform.iOS:
        return _iosForEnv;
      case TargetPlatform.macOS:
        return _macosForEnv;
      case TargetPlatform.windows:
        return _webForEnv;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for fuchsia - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }
  }

  static FirebaseOptions get _webForEnv {
    switch (firebaseEnv.toLowerCase()) {
      case 'dev':
      case 'develop':
      case 'development':
        return webDev;
      case 'stage':
      case 'staging':
        return webStaging;
      default:
        return web;
    }
  }

  static FirebaseOptions get _androidForEnv {
    switch (firebaseEnv.toLowerCase()) {
      case 'dev':
      case 'develop':
      case 'development':
        return androidDev;
      case 'stage':
      case 'staging':
        return androidStaging;
      default:
        return android;
    }
  }

  static FirebaseOptions get _iosForEnv {
    switch (firebaseEnv.toLowerCase()) {
      case 'dev':
      case 'develop':
      case 'development':
        return iosDev;
      case 'stage':
      case 'staging':
        return iosStaging;
      default:
        return ios;
    }
  }

  static FirebaseOptions get _macosForEnv {
    switch (firebaseEnv.toLowerCase()) {
      case 'dev':
      case 'develop':
      case 'development':
        return iosDev;
      case 'stage':
      case 'staging':
        return iosStaging;
      default:
        return ios;
    }
  }

  // ── Production (wishlist-wizard-prod) ──────────────────────────────────────

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbpeOZbE49Bx58pE-TZnSkb1C6LuXZYBY',
    appId: '1:464233600681:web:7591d99a2258b082957bb8',
    messagingSenderId: '464233600681',
    projectId: 'wishlist-wizard-prod',
    authDomain: 'wishlist-wizard-prod.firebaseapp.com',
    storageBucket: 'wishlist-wizard-prod.firebasestorage.app',
    measurementId: 'G-EVSC05Z24C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWBTcCm5NDaBvlBK251cAlBNnyuOAyyr8',
    appId: '1:464233600681:android:df14c48368aac2b0957bb8',
    messagingSenderId: '464233600681',
    projectId: 'wishlist-wizard-prod',
    storageBucket: 'wishlist-wizard-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-c5SJNvcvWYIJeM_c2fWyW6iusQeSXrQ',
    appId: '1:464233600681:ios:250d6d92b5066073957bb8',
    messagingSenderId: '464233600681',
    projectId: 'wishlist-wizard-prod',
    storageBucket: 'wishlist-wizard-prod.firebasestorage.app',
    iosBundleId: 'com.wishlistwizard.app.ios',
  );

  // ── Development (wishlist-wizard-dev) ─────────────────────────────────────

  static const FirebaseOptions webDev = FirebaseOptions(
    apiKey: 'AIzaSyBKaPCEKcIUaqn5GJNFNSBU799_wQPLCZo',
    appId: '1:1055615167809:web:4aa8734ea763474c5485c0',
    messagingSenderId: '1055615167809',
    projectId: 'wishlist-wizard-dev',
    authDomain: 'wishlist-wizard-dev.firebaseapp.com',
    storageBucket: 'wishlist-wizard-dev.firebasestorage.app',
    measurementId: 'G-R9N3G478FF',
  );

  static const FirebaseOptions androidDev = FirebaseOptions(
    apiKey: 'AIzaSyAvV2MI-A0pJAsCHu9mSIBXhZGNL42Qz8M',
    appId: '1:1055615167809:android:9dde4f0315d2dd075485c0',
    messagingSenderId: '1055615167809',
    projectId: 'wishlist-wizard-dev',
    storageBucket: 'wishlist-wizard-dev.firebasestorage.app',
  );

  static const FirebaseOptions iosDev = FirebaseOptions(
    apiKey: 'AIzaSyBO1gSdOqTIjNz1mWHSaZnhDc4hPNnlT6A',
    appId: '1:1055615167809:ios:a8a5633b35f7344c5485c0',
    messagingSenderId: '1055615167809',
    projectId: 'wishlist-wizard-dev',
    storageBucket: 'wishlist-wizard-dev.firebasestorage.app',
    iosBundleId: 'com.wishlistwizard.app.ios',
  );

  // ── Staging (wishlist-wizard-staging) ─────────────────────────────────────

  static const FirebaseOptions webStaging = FirebaseOptions(
    apiKey: 'AIzaSyA10PFvlDF4OenGG70hHEo4mIWbWJ10aVI',
    appId: '1:1039527515823:web:6b189a8d597a16d9dee65a',
    messagingSenderId: '1039527515823',
    projectId: 'wishlist-wizard-staging',
    authDomain: 'wishlist-wizard-staging.firebaseapp.com',
    storageBucket: 'wishlist-wizard-staging.firebasestorage.app',
    measurementId: 'G-49ZJQVE5GH',
  );

  static const FirebaseOptions androidStaging = FirebaseOptions(
    apiKey: 'AIzaSyCIeL17Pyydg7NAImCh64pwnvIV2RxPxrk',
    appId: '1:1039527515823:android:c72fe157d450914edee65a',
    messagingSenderId: '1039527515823',
    projectId: 'wishlist-wizard-staging',
    storageBucket: 'wishlist-wizard-staging.firebasestorage.app',
  );

  static const FirebaseOptions iosStaging = FirebaseOptions(
    apiKey: 'AIzaSyDd7wB94TpmEtIgyFeADs2iB0ll8E6BIMQ',
    appId: '1:1039527515823:ios:2dbf5a16f95d14fcdee65a',
    messagingSenderId: '1039527515823',
    projectId: 'wishlist-wizard-staging',
    storageBucket: 'wishlist-wizard-staging.firebasestorage.app',
    iosBundleId: 'com.wishlistwizard.app.ios',
  );
}
