// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for fuchsia - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXBMWTCbNDi2MhWxhZL9BQA3xEnGDEf70',
    appId: '1:1000918568663:web:143b262fb4bd8fd904ea92',
    messagingSenderId: '1000918568663',
    projectId: 'wishlist-wizard',
    authDomain: 'wishlist-wizard.firebaseapp.com',
    storageBucket: 'wishlist-wizard.firebasestorage.app',
    measurementId: 'G-75WET6CFDE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs93rijhaegkhZyanNyNBT9Ps2j8ZmrCM',
    appId: '1:1000918568663:android:4f0b526ad64522d704ea92',
    messagingSenderId: '1000918568663',
    projectId: 'wishlist-wizard',
    storageBucket: 'wishlist-wizard.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUFasexruct9M9HVzzG9o2S4upVeuks7c',
    appId: '1:1000918568663:ios:93f8e4c5e1480b6b04ea92',
    messagingSenderId: '1000918568663',
    projectId: 'wishlist-wizard',
    storageBucket: 'wishlist-wizard.firebasestorage.app',
    iosBundleId: 'com.nelsongrey.wishlistwizard.app.ios',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUFasexruct9M9HVzzG9o2S4upVeuks7c',
    appId: '1:1000918568663:ios:93f8e4c5e1480b6b04ea92',
    messagingSenderId: '1000918568663',
    projectId: 'wishlist-wizard',
    storageBucket: 'wishlist-wizard.firebasestorage.app',
    iosBundleId: 'com.nelsongrey.wishlistwizard.app.ios',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXBMWTCbNDi2MhWxhZL9BQA3xEnGDEf70',
    appId: '1:1000918568663:web:143b262fb4bd8fd904ea92',
    messagingSenderId: '1000918568663',
    projectId: 'wishlist-wizard',
    authDomain: 'wishlist-wizard.firebaseapp.com',
    storageBucket: 'wishlist-wizard.firebasestorage.app',
    measurementId: 'G-75WET6CFDE',
  );
}
