# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# All linting disabled for clean IDE experience
analyzer:
  errors:
    non_constant_identifier_names: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

include: package:flutter_lints/flutter.yaml

# All linting rules disabled
linter:
  rules: {}

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
