# Example mutations for a wishlist app

# Upsert (update or insert) a user's display name based on their auth.uid
mutation UpsertUser($displayName: String!, $email: String, $photoUrl: String) @auth(level: USER) {
  # The "auth.uid" server value ensures that users can only register their own user.
  user_upsert(data: { id_expr: "auth.uid", displayName: $displayName, email: $email, photoUrl: $photoUrl })
}
