mutation AddNewList @auth(level: USER) {
  list_insert(data: {
    userId_expr: "auth.uid",
    name: "My New List",
    description: "A wishlist of my favorite items",
    public: false,
    createdAt_expr: "request.time",
    updatedAt_expr: "request.time"
  })
}

query GetMyLists @auth(level: USER) {
  lists(where: {userId: {eq_expr: "auth.uid"}}) {
    id
    name
    description
    public
    createdAt
    updatedAt
  }
}