// GENERATED by video-production/scripts/gen-persona-dart.mjs. Do not edit.
const videoPersonas = <String, Map<String, String>>{
  'dahlia': {
    'id': 'dahlia',
    'email': 'dahlia.reyes@wishlist-wizard.video',
    'displayName': 'Dahlia Reyes',
    'tier': 'plus',
    'tagline': 'Every occasion, one place.',
  },
  'marcus': {
    'id': 'marcus',
    'email': 'marcus.bell@wishlist-wizard.video',
    'displayName': 'Marcus Bell',
    'tier': 'starter',
    'tagline': 'The gear you want. The price you want.',
  },
  'priya': {
    'id': 'priya',
    'email': 'priya.nair@wishlist-wizard.video',
    'displayName': 'Priya Nair',
    'tier': 'plus',
    'tagline': 'One gift. Twelve people. Zero spreadsheet.',
  },
  'priya_mobile': {
    'id': 'priya',
    'email': 'priya.nair@wishlist-wizard.video',
    'displayName': 'Priya Nair',
    'tier': 'plus',
    'tagline': 'One gift. Twelve people. Zero spreadsheet.',
  },
  'glenn': {
    'id': 'glenn',
    'email': 'glenn.okafor@wishlist-wizard.video',
    'displayName': 'Glenn Okafor',
    'tier': 'creator',
    'tagline': 'Your recommendations, working for you.',
  },
  'robin': {
    'id': 'robin',
    'email': 'robin.castellano@wishlist-wizard.video',
    'displayName': 'Robin Castellano',
    'tier': 'free',
    'tagline': 'The zero-friction way to get gifts you actually want.',
  },
};
