type User @table {
  displayName: String!
  email: String
  photoUrl: String
  createdAt: Timestamp!
}

type List @table {
  user: User!
  name: String!
  public: Boolean!
  description: String
  createdAt: Timestamp!
  updatedAt: Timestamp!
}